jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.x"
    - run: python -m pip install --upgrade build setuptools wheel
    - run: python -m build .
    - uses: pypa/gh-action-pypi-publish@release/v1
      with:
        skip-existing: true
name: Publish
on:
  push:
    branches:
      - main
