extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - toc:
      toc_depth: 3
      title: "&nbsp;"
plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_section_style: list
            docstring_style: numpy
            heading_level: 3
            line_length: 79
            merge_init_into_class: true
            parameter_headings: true
            separate_signature: true
            show_bases: false
            show_root_full_path: false
            show_root_heading: true
            show_root_toc_entry: true
            show_signature_annotations: true
            show_source: false
            signature_crossrefs: true
repo_name: "0x00b1/yeji"
repo_url: "https://github.com/0x00b1/yeji"
site_author: "Allen Goodman"
site_description: "Yeji (예지): A standard library for biological research."
site_name: "Yeji (예지)"
strict: true
theme:
  features:
    - navigation.sections
  name: "material"
nav:
  - "index.md"
  - "Package Reference":
    - "package_reference/yeji.md"
    - "package_reference/yeji.constants.md"
    - "package_reference/yeji.datasets.md"
    - "package_reference/yeji.features.md"
    - "package_reference/yeji.func.md"
    - "package_reference/yeji.lightning.md"
    - "package_reference/yeji.lightning.datamodules.md"
    - "package_reference/yeji.metrics.md"
    - "package_reference/yeji.metrics.functional.md"
    - "package_reference/yeji.transforms.md"
    - "package_reference/yeji.transforms.functional.md"
