[build-system]
requires = ["setuptools-scm>=8.0.4", "setuptools>=69.0.3", "wheel>=0.42.0"]
build-backend = "setuptools.build_meta"

[project]
authors = [{email = "allen.goodman@icloud.com", name = "Allen Goodman"}]
license = {file = "LICENSE"}
name = "yeji"
readme = "README.md"
requires-python = ">=3.10"
dynamic = ["version"]

[project.optional-dependencies]
development = []

[tool.setuptools_scm]
