AMINO_ACID_ATOMS = {
    "A": ["C", "CA", "CB", "N", "O"],
    "R": ["C", "CA", "CB", "CG", "CD", "CZ", "N", "NE", "O", "NH1", "NH2"],
    "D": ["C", "CA", "CB", "CG", "N", "O", "OD1", "OD2"],
    "N": ["C", "CA", "CB", "CG", "N", "ND2", "O", "OD1"],
    "C": ["C", "CA", "CB", "N", "O", "SG"],
    "E": ["C", "CA", "CB", "CG", "CD", "N", "O", "OE1", "OE2"],
    "Q": ["C", "CA", "CB", "CG", "CD", "N", "NE2", "O", "OE1"],
    "G": ["C", "CA", "N", "O"],
    "H": ["C", "CA", "CB", "CG", "CD2", "CE1", "N", "ND1", "NE2", "O"],
    "I": ["C", "CA", "CB", "CG1", "CG2", "CD1", "N", "O"],
    "L": ["C", "CA", "CB", "CG", "CD1", "CD2", "N", "O"],
    "K": ["C", "CA", "CB", "CG", "CD", "CE", "N", "NZ", "O"],
    "M": ["C", "CA", "CB", "CG", "CE", "N", "O", "SD"],
    "F": ["C", "CA", "CB", "CG", "CD1", "CD2", "CE1", "CE2", "CZ", "N", "O"],
    "P": ["C", "CA", "CB", "CG", "CD", "N", "O"],
    "S": ["C", "CA", "CB", "N", "O", "OG"],
    "T": ["C", "CA", "CB", "CG2", "N", "O", "OG1"],
    "W": [
        "C",
        "CA",
        "CB",
        "CG",
        "CD1",
        "CD2",
        "CE2",
        "CE3",
        "CZ2",
        "CZ3",
        "CH2",
        "N",
        "NE1",
        "O",
    ],
    "Y": [
        "C",
        "CA",
        "CB",
        "CG",
        "CD1",
        "CD2",
        "CE1",
        "CE2",
        "CZ",
        "N",
        "O",
        "OH",
    ],
    "V": ["C", "CA", "CB", "CG1", "CG2", "N", "O"],
}
