jobs:
  test:
    strategy:
      matrix:
        platform: [ macos-latest, ubuntu-latest, windows-latest ]
        python: [ "3.10", "3.11", "3.12" ]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}
    - run: python -m pip install --editable ".[test]"
    - run: python -m pytest
name: Test
on: [ pull_request, push ]
