jobs:
  test:
    strategy:
      matrix:
        platform: [ macos-latest, ubuntu-latest, windows-latest ]
        python: [ "3.10", "3.11" ]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - run: python -m pip install --editable ".[all]"
      - run: python -m pytest
      - env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        uses: codecov/codecov-action@v3
name: Test
on: [ pull_request, push ]
